version: '3.8'

services:
  app:
    build: .
    container_name: crm-symfony-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/crm_db
    networks:
      - crm

  db:
    image: mysql:8.0
    container_name: crm-symfony-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crm

volumes:
  db_data:

networks:
  crm:
