global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'symfony-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
