parameters:
    api_base_url: '%env(API_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\User\UserServiceInterface:
        alias: App\Service\User\UserService
    App\Service\Client\ClientServiceInterface:
        alias: App\Service\Client\ClientService

   