- name: Déploiement de l'application Symfony
  hosts: localhost
  become: true  # <--- AJOUTE CETTE LIGNE
  tasks:
    - name: Copier le code Symfony localement
      synchronize:
        src: ..
        dest: /opt/crm-symfony/
        recursive: yes
        delete: yes

    - name: Copier le fichier docker-compose
      copy:
        src: ../docker-compose.yml
        dest: /opt/crm-symfony/docker-compose.yml

    - name: Lancer le conteneur Docker Compose
      shell: docker compose -f /opt/crm-symfony/docker-compose.yml up -d --build
