- name: Déploiement de l'application Symfony
  hosts: serveur
  become: true

  tasks:
    - name: Copier le projet Symfony
      synchronize:
        src: ..
        dest: /opt/crm-symfony/
        recursive: yes
        delete: yes

    - name: Copier le fichier docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: /opt/crm-symfony/docker-compose.yml

    - name: Lancer le conteneur avec Docker Compose
      shell: docker compose -f /opt/crm-symfony/docker-compose.yml up -d --build
